"""empty message

Revision ID: fae5ef00946c
Revises: 696f9dd8194f
Create Date: 2024-10-20 16:54:07.912880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fae5ef00946c'
down_revision: Union[str, None] = '696f9dd8194f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiomodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiomodel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
